import {useCallback,useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import type {Battle,Dialogue,Direction,OtherPlayer,Player,Pokemon,Result,World} from './types';
import {ApiError,request} from './api';
import {nearby,pathTo,WorldRenderer} from './world';
import './style.css';

const typeNames:Record<string,string>={Grass:'Plante',Fire:'Feu',Water:'Eau',Normal:'Normal',Flying:'Vol',Bug:'Insecte',Electric:'Électrik',Rock:'Roche',Ground:'Sol',Poison:'Poison',Psychic:'Psy',Ice:'Glace',Fighting:'Combat',Ghost:'Spectre',Dark:'Ténèbres',Dragon:'Dragon',Steel:'Acier',Fairy:'Fée'};
const names:Record<number,string>={10:'Chenipan',16:'Roucool',19:'Rattata',25:'Pikachu',41:'Nosferapti',74:'Racaillou',152:'Germignon',155:'Héricendre',158:'Kaiminus',163:'Hoothoot'};
function Icon({name,size=22}:{name:string;size?:number}){
 const paths:Record<string,React.ReactNode>={
  ball:<><path d="M3 12h6m6 0h6"/><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="3"/></>,
  bag:<><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M5 8a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2zM8 14h8v5H8zM8 10h8"/></>,
  book:<><path d="M4 3h15v18H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Zm2 0v18M10 7h5M10 11h5"/></>,
  map:<><path d="m3 5 6-3 6 3 6-3v17l-6 3-6-3-6 3V5Zm6-3v17m6-14v17"/></>,
  menu:<><path d="M4 6h16M4 12h16M4 18h16"/></>,
  close:<path d="m6 6 12 12M6 18 18 6"/>,
  arrow:<path d="M5 12h14m-6-6 6 6-6 6"/>,
  people:<><circle cx="9" cy="7" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-16a3 3 0 0 1 0 6m2 3a5 5 0 0 1 3 4v3"/></>,
  leaf:<><path d="M20 3C6 2 1 9 5 16s17 2 15-13ZM4 21l11-12"/></>,
  star:<path d="m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z"/>,
  potion:<><path d="M9 2h6v5l4 5v9H5v-9l4-5V2Zm-1 1h8M8 14h8m-4-4v8"/></>,
  sound:<><path d="m3 9 5 0 5-5v16l-5-5H3V9Zm14-2a7 7 0 0 1 0 10"/></>,
  exit:<><path d="M9 4H3v16h6m5-13 5 5-5 5m-7-5h12"/></>,
  check:<path d="m5 12 4 4L19 6"/>,
 };
 return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths.ball}</svg>;
}
function Types({pokemon}:{pokemon:Pokemon}){return <span className="types">{pokemon.types.map(t=><span key={t} className={`type type-${t.toLowerCase()}`}>{typeNames[t]||t}</span>)}</span>}
function Hp({pokemon,numbers=true}:{pokemon:Pokemon;numbers?:boolean}){const percent=100*pokemon.hp/pokemon.maxHp;return <div className="hp-block"><div className="hp-line"><span>PV</span><div className="hp-track"><i className={percent<25?'low':percent<50?'medium':''} style={{width:`${percent}%`}}/></div>{numbers&&<small>{pokemon.hp} / {pokemon.maxHp}</small>}</div></div>}
function Modal({title,kicker,children,close}:{title:string;kicker?:string;children:React.ReactNode;close:()=>void}){
 const box=useRef<HTMLDivElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;box.current?.focus();return()=>previous?.focus()},[]);
 return <div className="modal-shade" onPointerDown={e=>{if(e.target===e.currentTarget)close()}}><section ref={box} className="modal" role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} onKeyDown={e=>{if(e.key==='Tab'){const elements=box.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,a[href]');if(elements?.length){const first=elements[0],last=elements[elements.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===box.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}}><header><div>{kicker&&<span className="eyebrow">{kicker}</span>}<h2>{title}</h2></div><button className="icon-button" onClick={close} aria-label="Fermer"><Icon name="close"/></button></header>{children}</section></div>;
}
function Login({onLogin,busy}:{onLogin:(action:string,values:Record<string,unknown>)=>Promise<void>;busy:boolean}){
 const[register,setRegister]=useState(false),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[avatar,setAvatar]=useState('male'),[validation,setValidation]=useState('');
 return <div className="welcome"><div className="welcome-copy"><div className="brand"><Icon name="ball" size={27}/><span>ABSOLUTE</span><span className="brand-edition">EXPLORATION</span></div><p className="eyebrow">Un nouveau départ</p><h1>Le monde n’attend<br/>que <em>vos premiers pas.</em></h1><p className="intro">Un compagnon à vos côtés. Des sentiers à découvrir.<br/>Et, dans les hautes herbes, votre prochaine rencontre.</p><div className="welcome-features"><span><Icon name="leaf" size={17}/>Explorez librement</span><span><Icon name="people" size={17}/>Croisez d’autres dresseurs</span></div></div><section className="login-card"><span className="eyebrow">Votre carnet de voyage</span><h2>{register?'Tout commence ici.':'Reprendre la route.'}</h2><p>{register?'Créez votre personnage. Votre premier Pokémon vous attend au laboratoire.':'Connectez-vous avec votre compte Absolute. Votre compagnon vous attend.'}</p><form onSubmit={e=>{e.preventDefault();if(register&&password!==confirm){setValidation('Les mots de passe ne correspondent pas.');return}setValidation('');void onLogin(register?'register':'login',{username,password,avatar})}}><label>Pseudo<input name="username" autoComplete="username" minLength={register?3:1} maxLength={register?20:255} required value={username} onChange={e=>setUsername(e.target.value)} placeholder="Votre nom de dresseur"/></label><label>Mot de passe<input name="password" type="password" autoComplete={register?'new-password':'current-password'} minLength={register?8:1} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)} placeholder={register?'8 caractères minimum':'Votre mot de passe'}/></label>{register&&<><label>Confirmer le mot de passe<input type="password" autoComplete="new-password" required value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><fieldset className="avatar-choice"><legend>Votre personnage</legend>{['male','female'].map((a,i)=><button key={a} type="button" aria-pressed={avatar===a} className={avatar===a?'selected':''} onClick={()=>setAvatar(a)}><span className={`trainer-preview trainer-${a}`}/>{i===0?'Dresseur':'Dresseuse'}</button>)}</fieldset></>}{validation&&<p className="form-error" role="alert">{validation}</p>}<button className="primary" disabled={busy}>{busy?'Un instant…':register?'Commencer mon aventure':'Continuer l’aventure'}<Icon name="arrow" size={20}/></button></form><div className="login-switch">{register?'Déjà un compte ?':'Votre première visite ?'} <button onClick={()=>{setRegister(!register);setValidation('')}}>{register?'Se connecter':'Créer un personnage'}</button></div><div className="save-note"><span className="status-dot"/>Progression sauvegardée sur votre compte</div></section><div className="welcome-bottom"><span>BOURG AURORE · RÉGION ABSOLUTE</span><span>Explorez. Rencontrez. Collectionnez.</span></div></div>;
}
function Starter({starters,busy,choose}:{starters:Pokemon[];busy:boolean;choose:(id:number)=>void}){
 const[selected,setSelected]=useState<number|null>(null);
 return <div className="starter-overlay"><section className="starter-scene"><span className="eyebrow">Laboratoire du Pr. Aulne</span><h2>Chaque aventure commence<br/>par une <em>rencontre.</em></h2><p>Trois compagnons. Mille chemins possibles. Lequel choisirez-vous ?</p><div className="starter-options">{starters.map((p,i)=><button key={p.dexId} onClick={()=>setSelected(p.dexId)} className={`starter-choice starter-${p.types[0].toLowerCase()} ${selected===p.dexId?'chosen':''}`} aria-pressed={selected===p.dexId}><span className="starter-number">0{i+1}</span><div className="starter-image"><img src={p.sprite} alt={p.name}/></div><h3>{p.name}</h3><Types pokemon={p}/><p>{i===0?'Doux et curieux, toujours prêt à explorer.':i===1?'Un petit feu qui ne demande qu’à grandir.':'Une énergie débordante et un grand cœur.'}</p><span className="choose-marker"><Icon name={selected===p.dexId?'check':'ball'} size={18}/>{selected===p.dexId?'Mon compagnon':'Faire connaissance'}</span></button>)}</div><button className="primary choose-starter" disabled={selected===null||busy} onClick={()=>selected&&choose(selected)}>{busy?'La rencontre se prépare…':selected?'Partir ensemble':'Choisissez votre compagnon'}<Icon name="arrow"/></button><small>Votre choix est définitif. Votre compagnon commence au niveau 5.</small></section></div>;
}
function BattleScene({battle,active,bag,busy,act,openTeam}:{battle:Battle;active:Pokemon;bag:Player['bag'];busy:boolean;act:(a:string,d?:Record<string,unknown>)=>void;openTeam:()=>void}){
 const[moves,setMoves]=useState(false);
 useEffect(()=>{setMoves(false)},[battle.turn,battle.id]);
 return <div className="battle-overlay" role="region" aria-label="Combat sauvage"><div className="battle-scene"><div className="battle-atmosphere"/><div className="battle-caption"><span className="status-dot"/>RENCONTRE SAUVAGE</div><div className="combat-card wild-card"><div><strong>{battle.wild.name}{battle.wild.shiny?' ✦':''}</strong><span>Niv. {battle.wild.level}</span></div><Hp pokemon={battle.wild} numbers={false}/><Types pokemon={battle.wild}/></div><div className={`wild-platform ${battle.outcome==='caught'?'captured':''}`}><img key={battle.id} className={battle.wild.hp===0?'fainted':''} src={battle.wild.sprite} alt={battle.wild.name}/></div><div className="own-platform"><img className={active.hp===0?'fainted':''} src={active.sprite} alt={active.name}/></div><div className="combat-card own-card"><div><strong>{active.name}</strong><span>Niv. {active.level}</span></div><Hp pokemon={active}/><div className="exp-track"><i style={{width:`${Math.min(100,100*(active.experience-active.levelFloor)/(active.nextLevel-active.levelFloor))}%`}}/></div></div><div className="battle-console"><div className="battle-log" aria-live="polite"><span className="eyebrow">{battle.outcome?'La rencontre s’achève':`Tour ${battle.turn+1}`}</span>{battle.log.map((line,i)=><p key={`${battle.turn}-${i}`}>{line}</p>)}{busy&&<span className="resolving">Le combat se poursuit…</span>}</div>{battle.outcome?<div className="battle-actions"><button className="primary" disabled={busy} onClick={()=>act('finish')}>Reprendre l’exploration<Icon name="arrow"/></button></div>:moves?<div className="battle-actions move-actions">{active.moves.map((m,i)=><button key={m.id} className={`move-button type-border-${m.type.toLowerCase()}`} disabled={busy||m.pp===0} onClick={()=>act('attack',{move:i})}><strong>{m.name}</strong><span>{typeNames[m.type]||m.type}<small>{m.pp} / {m.maxPp} PP</small></span></button>)}<button className="text-button" onClick={()=>setMoves(false)}>Retour</button></div>:<div className="battle-actions"><button className="battle-main" disabled={busy} onClick={()=>setMoves(true)}>Attaquer<Icon name="star"/></button><button disabled={busy||bag.balls===0} onClick={()=>act('capture')}><Icon name="ball"/>Capturer<small>{bag.balls} Poké Balls</small></button><button disabled={busy||bag.potions===0||active.hp===active.maxHp} onClick={()=>act('potion')}><Icon name="potion"/>Potion<small>{bag.potions} dans le sac</small></button><button disabled={busy} onClick={openTeam}><Icon name="people"/>Équipe</button><button disabled={busy} onClick={()=>act('run')}><Icon name="exit"/>Fuir</button></div>}</div></div></div>;
}
function App(){
 const[world,setWorld]=useState<World|null>(null),[starters,setStarters]=useState<Pokemon[]>([]),[player,setPlayer]=useState<Player|null>(null),[others,setOthers]=useState<OtherPlayer[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dialogue,setDialogue]=useState<Dialogue|null>(null),[panel,setPanel]=useState<string|null>(null),[connected,setConnected]=useState(true);
 const canvas=useRef<HTMLCanvasElement>(null),renderer=useRef<WorldRenderer|null>(null),playerRef=useRef(player),worldRef=useRef(world),busyRef=useRef(false),blocked=useRef(false),keys=useRef(new Set<string>()),path=useRef<Direction[]>([]),touch=useRef<Direction|null>(null),actionRef=useRef<(a:string,d?:Record<string,unknown>)=>Promise<void>>(async()=>{}),interactionRef=useRef(()=>{});
 playerRef.current=player;worldRef.current=world;blocked.current=!!(panel||dialogue||player?.battle||!player);
 const apply=useCallback((r:Result)=>{if(r.player!==undefined){setPlayer(r.player);playerRef.current=r.player}if(r.world){setWorld(r.world);worldRef.current=r.world}if(r.starters)setStarters(r.starters)},[]);
 const boot=useCallback(async()=>{setLoading(true);try{apply(await request('bootstrap'));setError('');setConnected(true)}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[apply]);
 useEffect(()=>{void boot()},[boot]);
 useEffect(()=>{if(!world||!canvas.current)return;const scene=new WorldRenderer(canvas.current,world);renderer.current=scene;scene.player=playerRef.current;return()=>{scene.destroy();renderer.current=null}},[world]);
 useEffect(()=>{if(renderer.current){renderer.current.player=player;renderer.current.others=others}},[player,others]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),5500);return()=>clearTimeout(timer)},[notice]);
 const act=useCallback(async(action:string,data:Record<string,unknown>={})=>{
  const current=playerRef.current;if(busyRef.current||!current)return;busyRef.current=true;setBusy(true);setError('');
  try{const r=await request(action,{...data,revision:current.revision});apply(r);setConnected(true);if(r.notice)setNotice(r.notice);if(r.dialogue)setDialogue(r.dialogue);if(action==='starter'){setDialogue(null);setPanel(null)}if(r.player?.position.map!==current.position.map||r.player?.battle){path.current=[];keys.current.clear();touch.current=null;}if(action==='switch')setPanel(null)}
  catch(e){const err=e as ApiError;if(err.status!==429){setError(err.message);path.current=[];keys.current.clear();touch.current=null;}if(err.status===0)setConnected(false);try{apply(await request('bootstrap'))}catch{/* Keep the last acknowledged position visible while offline. */}}
  finally{busyRef.current=false;setBusy(false)}
 },[apply]);actionRef.current=act;
 const interact=()=>{const p=playerRef.current,w=worldRef.current;if(!p||!w||blocked.current||busyRef.current)return;const o=nearby(w.maps[p.position.map],p);if(o)void act('interact',{object:o.id})};interactionRef.current=interact;
 useEffect(()=>{
  if(!player)return;let stopped=false,running=false;
  const poll=async()=>{if(running||busyRef.current)return;running=true;const map=playerRef.current?.position.map;
   try{const r=await request('presence');if(stopped)return;setConnected(true);if(playerRef.current?.position.map===map)setOthers(r.players||[]);if(r.revision!==playerRef.current?.revision&&!busyRef.current){const snapshot=await request('state');if(!stopped&&!busyRef.current)apply(snapshot)}}catch{if(!stopped)setConnected(false)}finally{running=false}};
  void poll();const timer=setInterval(poll,1100);return()=>{stopped=true;clearInterval(timer);setOthers([])};
 },[player?.user.id,apply]);
 useEffect(()=>{
  const down=(e:KeyboardEvent)=>{
   if((e.target as HTMLElement)?.closest('input,textarea,select'))return;
   const key=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','z','q','s','d','w','a',' ','e'].includes(key))e.preventDefault();
   if(key==='escape'){setPanel(null);setDialogue(null);keys.current.clear();path.current=[];return}
   if((key==='e'||key===' ')&&!e.repeat){interactionRef.current();return}
   if(key==='i'&&!e.repeat){setPanel(p=>p==='bag'?null:'bag');return}
   if(key==='j'&&!e.repeat){setPanel(p=>p==='journal'?null:'journal');return}
   if(!blocked.current){keys.current.add(key);if(key!=='shift')path.current=[]}
  };
  const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const blur=()=>{keys.current.clear();path.current=[];touch.current=null};
  window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);
  let frame=0,last=0;const tick=(time:number)=>{if(!blocked.current&&!busyRef.current&&time-last>(keys.current.has('shift')?115:175)){
   const map:Record<string,Direction>={arrowup:'up',z:'up',w:'up',arrowdown:'down',s:'down',arrowleft:'left',q:'left',a:'left',arrowright:'right',d:'right'};
   const key=[...keys.current].reverse().find(k=>map[k]);const direction=touch.current||(key?map[key]:undefined)||path.current.shift();
   if(direction){last=time;void actionRef.current('move',{direction})}
  }frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);
  return()=>{cancelAnimationFrame(frame);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur)};
 },[]);
 const login=async(action:string,data:Record<string,unknown>)=>{if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');try{apply(await request(action,data));setConnected(true);setNotice(action==='register'?'Bienvenue au laboratoire. Approchez-vous du professeur et appuyez sur E.':'Votre aventure reprend là où vous l’avez laissée.')}catch(e){setError((e as Error).message)}finally{busyRef.current=false;setBusy(false)}};
 const logout=async()=>{if(busyRef.current)return;busyRef.current=true;setBusy(true);try{apply(await request('logout',{}));setPanel(null);setDialogue(null);setOthers([])}catch(e){setError((e as Error).message)}finally{busyRef.current=false;setBusy(false)}};
 const active=player?.team.find(p=>p.id===player.activeId)||player?.team[0],zone=world&&player?world.maps[player.position.map]:null,object=zone&&player?nearby(zone,player):null;
 return <main className={`app ${!player?'at-title':''}`}>
  {world&&<canvas ref={canvas} className="world-canvas" aria-label="Monde d’exploration. Déplacez-vous avec les flèches ou ZQSD, E pour interagir." tabIndex={0} onClick={e=>{if(blocked.current||!playerRef.current||!worldRef.current||!renderer.current)return;const tile=renderer.current.tileAt(e.clientX,e.clientY);path.current=pathTo(worldRef.current.maps[playerRef.current.position.map],playerRef.current.position,tile);canvas.current?.focus()}}/>}
  {!world&&<div className="loading-world"><Icon name="ball" size={48}/><h1>Absolute</h1><p>{loading?'Le monde se réveille…':'Le monde est momentanément indisponible.'}</p>{!loading&&<button className="primary" onClick={()=>void boot()}>Réessayer</button>}</div>}
  {world&&!player&&<Login onLogin={login} busy={busy}/>}
  {world&&player&&zone&&<>
   <div className="world-vignette"/>
   <header className="game-hud"><div className="location-badge" key={zone.id}><div className="location-symbol"><Icon name={zone.kind==='outdoor'?'leaf':zone.kind==='cave'?'star':'ball'} size={24}/></div><div><span className="eyebrow">Région Absolute</span><h1>{zone.name}</h1><span className="location-detail">{zone.subtitle}</span></div></div><div className="hud-right"><span className={`connection ${connected?'':'disconnected'}`} title="Les dresseurs présents dans votre zone"><span className="status-dot"/>{connected?<><Icon name="people" size={15}/>{others.length+1}</>:'Hors ligne'}</span><button className="trainer-button" onClick={()=>setPanel('menu')} aria-label="Ouvrir le menu"><span className="trainer-initial">{player.user.name.slice(0,1).toUpperCase()}</span><span>{player.user.name}</span><Icon name="menu" size={19}/></button></div></header>
   {!player.battle&&<><div className="journey-note"><span className="eyebrow">Votre prochaine étape</span><p>{player.needsStarter?'Rencontrer le Pr. Aulne':player.caught.length<2?'Faire votre première capture':!player.visited.includes('grove')?'Découvrir la Clairière des Murmures':!player.visited.includes('cave')?'Explorer la Grotte Cristalline':'Continuer à découvrir la région'}</p><span>{player.needsStarter?'Approchez-vous et appuyez sur E':player.caught.length<2?'Les hautes herbes du sentier vous attendent':'Chaque détour réserve une rencontre.'}</span></div><footer className="game-footer"><div className="companion">{active?<><img src={active.icon} alt=""/><div><span className="eyebrow">À vos côtés</span><strong>{active.name}<small>Niv. {active.level}</small></strong><Hp pokemon={active} numbers={false}/></div></>:<div><span className="eyebrow">Le début du voyage</span><strong>Un compagnon vous attend</strong></div>}</div><div className="action-dock">{[['team','ball','Équipe'],['bag','bag','Sac'],['journal','book','Carnet'],['region','map','Région']].map(([id,icon,label])=><button key={id} onClick={()=>{keys.current.clear();path.current=[];setPanel(id)}} aria-label={label}><Icon name={icon}/><span>{label}</span></button>)}</div></footer><div className="movement-help"><span><kbd>↑</kbd><kbd>←</kbd><kbd>↓</kbd><kbd>→</kbd> ou ZQSD</span><span><kbd>MAJ</kbd> courir</span><span>Cliquez pour marcher</span></div>{object&&!dialogue&&!panel&&<button className="interaction-prompt" onClick={interact}><kbd>E</kbd>{object.kind==='item'?'Ramasser':object.kind==='sign'?'Lire':`Parler à ${object.name}`}</button>}<div className="touch-controls"><div className="dpad">{(['up','left','down','right'] as Direction[]).map((d,i)=><button key={d} className={`pad-${d}`} aria-label={`Marcher ${d}`} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);touch.current=d}} onPointerUp={()=>touch.current=null} onPointerCancel={()=>touch.current=null} onLostPointerCapture={()=>touch.current=null}>{['↑','←','↓','→'][i]}</button>)}</div><button className="touch-interact" onClick={interact}>E</button></div></>}
   {player.battle&&active&&<BattleScene battle={player.battle} active={active} bag={player.bag} busy={busy} act={(a,d)=>void act(a,d)} openTeam={()=>setPanel('team')}/>}
   {dialogue?.starter?<Starter starters={starters} busy={busy} choose={species=>void act('starter',{species})}/>:dialogue&&<div className="dialogue-wrap"><section className="dialogue" role="dialog" aria-label={dialogue.name}><div className="dialogue-speaker"><Icon name="leaf" size={18}/>{dialogue.name}</div><p>{dialogue.text}</p><button onClick={()=>setDialogue(null)}>Continuer<Icon name="arrow" size={18}/></button></section></div>}
   {panel==='team'&&<Modal title="Vos compagnons" kicker="Une équipe, une aventure" close={()=>setPanel(null)}><div className="team-grid">{player.team.map(p=><button key={p.id} className={`team-card ${p.id===active?.id?'active':''}`} disabled={busy||(!!player.battle&&(p.hp===0||p.id===active?.id))} onClick={()=>void act('switch',{pokemon:p.id})}><img src={p.sprite} alt={p.name}/><div><div className="pokemon-title"><strong>{p.name}</strong><small>Niv. {p.level}</small></div><Types pokemon={p}/><Hp pokemon={p}/><span className="team-role">{p.id===active?.id?'À vos côtés':p.hp===0?'Besoin de soins':'Choisir ce compagnon'}</span></div></button>)}{!player.team.length&&<p className="empty-state">Votre premier compagnon vous attend au laboratoire.</p>}</div>{player.collection.length>0&&<><h3 className="reserve-title">La réserve · {player.collection.length} Pokémon</h3><div className="reserve-grid">{player.collection.map(p=><span key={p.id}><img src={p.icon} alt=""/>{p.name}<small>Niv. {p.level}</small></span>)}</div></>}<p className="modal-footnote">Le premier compagnon marche avec vous. Un changement pendant un combat utilise votre tour.</p></Modal>}
   {panel==='bag'&&<Modal title="Votre sac de voyage" kicker="Toujours prêt pour la prochaine rencontre" close={()=>setPanel(null)}><div className="bag-list"><div><span className="item-art"><Icon name="ball" size={42}/></span><div><h3>Poké Ball</h3><p>Pour capturer un Pokémon sauvage. Affaiblissez-le d’abord pour augmenter vos chances.</p></div><strong>× {player.bag.balls}</strong></div><div><span className="item-art potion-art"><Icon name="potion" size={42}/></span><div><h3>Potion</h3><p>Restaure jusqu’à 20 PV à votre compagnon actif.</p><button className="text-button" disabled={busy||!active||active.hp<=0||active.hp===active.maxHp||player.bag.potions===0} onClick={()=>void act('potion')}>Soigner {active?.name||'votre compagnon'}</button></div><strong>× {player.bag.potions}</strong></div></div><p className="modal-footnote">Gardez l’œil ouvert : des objets attendent d’être découverts sur les chemins. Les soins du Centre Pokémon sont gratuits.</p></Modal>}
   {panel==='journal'&&<Modal title="Le carnet des rencontres" kicker="Les souvenirs prennent vie" close={()=>setPanel(null)}><div className="journal-stats"><span><b>{player.seen.length}</b>espèces rencontrées</span><span><b>{player.caught.length}</b>espèces capturées</span><span><b>{player.steps.toLocaleString('fr-FR')}</b>pas d’exploration</span></div><div className="dex-grid">{[...new Set([...Object.keys(names).map(Number),...player.seen])].sort((a,b)=>a-b).map(id=><div key={id} className={!player.seen.includes(id)?'undiscovered':''}><span className="dex-number">#{String(id).padStart(3,'0')}</span><img src={`/images/Pokemon/Sprites/Normal/${id}.png`} alt={player.seen.includes(id)?names[id]||`Pokémon ${id}`:'Espèce inconnue'}/><strong>{player.seen.includes(id)?names[id]||player.team.find(p=>p.dexId===id)?.name||`Pokémon ${id}`:'???'}</strong><small>{player.caught.includes(id)?'Capturé':player.seen.includes(id)?'Rencontré':'À découvrir'}</small></div>)}</div></Modal>}
   {panel==='region'&&<Modal title="Une région à découvrir" kicker="Suivez les chemins" close={()=>setPanel(null)}><div className="region-map"><div className="region-line"/>{['grove','route','village','cave'].map(id=><div key={id} className={`region-place place-${id} ${player.position.map===id?'here':''} ${player.visited.includes(id)?'visited':''}`}><Icon name={id==='cave'?'star':id==='village'?'ball':'leaf'} size={26}/><strong>{world.maps[id].name}</strong><span>{player.position.map===id?'Vous êtes ici':player.visited.includes(id)?'Découvert':'À explorer'}</span></div>)}</div><p className="modal-footnote">Rejoignez chaque lieu en marchant jusqu’aux passages. Le laboratoire et le Centre Pokémon se trouvent à Bourg Aurore.</p></Modal>}
   {panel==='menu'&&<Modal title={player.user.name} kicker="Votre aventure Absolute" close={()=>setPanel(null)}><div className="menu-save"><Icon name="check"/><div><strong>Votre progression est sauvegardée</strong><p>Position, équipe, captures et découvertes sont liées à votre compte.</p></div></div><div className="controls-guide"><h3>Prendre les chemins</h3><p><kbd>↑ ← ↓ →</kbd> ou <kbd>ZQSD / WASD</kbd> Se déplacer</p><p><kbd>MAJ</kbd> Courir · <kbd>E</kbd> Interagir</p><p><kbd>I</kbd> Sac · <kbd>J</kbd> Carnet · <kbd>ÉCHAP</kbd> Fermer</p><p>Vous pouvez aussi cliquer une case du monde pour vous y rendre.</p></div><button className="logout-button" disabled={busy} onClick={()=>void logout()}><Icon name="exit"/>Quitter la session</button></Modal>}
  </>}
  {notice&&<div className="notice" role="status"><Icon name="check" size={18}/>{notice}</div>}
  {error&&<div className="error-toast" role="alert"><span>{error}</span><button onClick={()=>setError('')} aria-label="Fermer le message"><Icon name="close" size={18}/></button></div>}
 </main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
